name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run Ruff
      uses: chartboost/ruff-action@v1
